### ISSUE TITLE
Out of bounds block is processed in SliceGuarantor

### ISSUE THREAD

**Issue by funkey** [catsop/catsop#12]
When requesting block (0,0,20) in a stack of size (1024,1024,20) with block size (16,16,8) the expected return would be that the images for the requested block are missing. Instead, I get

  0x24e4a40 [SliceGuarantor] Guaranteeing slices for region [0, 0, 16; 16, 16, 20]

and later

  0x24e4a40 [pysopnet] [SliceGuarantor] 0 blocks missing

**Comment by larrylindsey** [comment]
How big is the physical stack? In other words, are there 20 sections?

If not, then this is probably due to the implementation of LocalStackStore. I'll take a look at it. It is on my list of things to do to figure out what should happen when there is a geometry violation.

**Comment by funkey** [comment]
Yes, the size of the stack is (1024,1024,20). Find it in test/python.

**Comment by larrylindsey** [comment]
OK. looks like there's a one-off error. Are you calling getBlockAtCoordinates or getBlockAtLocation?

**Comment by funkey** [comment]
I use getBlockAtLocation like so: https://github.com/catsop/python-sopnet/blob/master/pysopnet/SliceGuarantor.cpp#L25

**Comment by larrylindsey** [comment]
I'm looking through the code again, and I think the behavior you describe is as designed. I have tried to avoid the necessity for exceptions, because I think it would become overly complicated in a server/client model.

The BlockManager centers around the getBlockAtCoordinates() method, which returns a block given its 0-index integer coordinates. For instance, if Block size is [512 512 16], then getBlockAtCoordinates(util::point3<unsigned int>(1, 1, 1)); returns the block from [512 512 16] to [1024 1024 32](keeping in mind that its closed-open).

getBlockAtCoordinates is supposed to return a null Block if the requested coordinates are invalid, and Blocks is designed to handle this case. In other words, if you create a Blocks object from a collection of invalid Block objects, you'll get an empty collection, so requesting SliceGuarantor with this input does exactly nothing.

**Comment by larrylindsey** [comment]
the link 1024 1024 32 should have read "1024 1024 32, keeping in mind that blocks are closed-open." I would edit, but my browser is apparently broken wrt to github :(

**Comment by unidesigner** [comment]
Are invalid coordinates only out-of-bound coordinates. Are there other exceptions that return a null Block? What happens if you pass floating point coordinates?

**Comment by larrylindsey** [comment]
Yes, coordinates are valid iff they are within the accepted limits. There
are no other conditions under which blocks would be considered invalid by
the BlockManager. If you passed floating-point coordinates, you'd get a
compiler-time error because coordinates are defined as
util::point3<unsigned int>

**Comment by funkey** [comment]
This does not explain why I read

```
0x24e4a40 [SliceGuarantor] Guaranteeing slices for region [0, 0, 16; 16, 16, 20]
```

in the logs.

How do you suggest can I figure out if a block request is invalid from the calling side?

**Comment by larrylindsey** [comment]
Interesting. I'll double check the code.

How would you feel about
bool BlockManager::isValidCoordinate(const util::point3<unsigned int> coords);
and
bool BlockManager::isValidLocation(const util::point<unsigned int> loc);
?

**Comment by unidesigner** [comment]
What does location refer to? To me, Coordinate and Location is a bit confusing, both sound like stack voxel coordinates. For clarity, Coordinate could be BlockCoordinate.

**Comment by larrylindsey** [comment]
For Box/Block/Core notation, location and size refer to the physical metric space, while coordinates are measured in Block's or Core's. For instance, coordinate [1, 2, 3] represents the block whose infimum is at the location 1_w,2_h,3*d, where [w,h,d] is the block size.

I'm not sure that calling it blockCoordinate or coreCoordinate would do much to clarify. Another name might do, though. I'll think on it.

**Comment by funkey** [comment]
```
bool BlockManager::isValidCoordinate(const util::point3 coords);
bool BlockManager::isValidLocation(const util::point loc);
```

...sounds good to me.

**Comment by larrylindsey** [comment]
Bugfix in ce4eac2b290c63c950dedafb14e97c4471e1cae2. Would you verify and close?

**Comment by funkey** [comment]
Solved, thank you.
