### ISSUE TITLE
Speedup connected-component / assembly computation in a Core

### ISSUE THREAD

**Issue by unidesigner** [catsop/catsop#41]
As @aschampion we could implement it in C++ instead of currently Python/NetworkX. Another option which would possibly prevent the need for serialization and deserialization steps is to implement it in Postgres directly, even PL/Python yields considerable speedup, [see](http://stackoverflow.com/questions/27967093/how-to-aggregate-matching-pairs-into-connected-components-in-python)

**Comment by aschampion** [comment]
While I prefer minimizing the responsibility of each guarantor, it might make sense to do this in the solution guarantor. It already has the solution and segment graph loaded in memory, and there isn't really any case where we would want to generate a solution but not assemblies. Plus this would be trivial to implement given that lemon graph is now being used elsewhere in SOPNET.

This relates to another point, that if we deduplicate assemblies (which is needed for diffs for parsimonious updates of the assembly multigraph) it's much more efficient to store solutions as sets of assemblies associated to a solution rather than sets of segments associated to a solution. In this case the solution guarantor would be required to compute assemblies anyway. Of course there are tradeoffs involved but we can talk through those in person sometime.

**Comment by unidesigner** [comment]
I agree - it makes more sense as you suggest to that it as part of the solution guarantor, all data is in memory. The connected-component generation could be implemented as a reusable Sopnet processing node. I imagine that we might want to extract connected components from larger-than-core volumes with sparser set of slices.

Associating the assemblies as solution precedence instead of segments makes a lot of sense, haven't thought about it - its much more efficient. What would be the approach to compute assembly deltas? Difference computation must happen at the level of connected segments I guess. Maybe computing a hash based on the set of segment ids in a connected component would allow for fast set intersections between previous and current solution. Generally, I think we should do things as high up in the hierarchy as possible.

**Comment by aschampion** [comment]
Hashing was the plan all the way up and down the hierarchy, although things like solutions should have both a hash and an independent id because of different statefulness concerns. Also for assemblies (unlike every other hashed object we have) there's the nice property that the hashes don't need to be globally unique. Determining whether the collision prevention and mitigation is worth the database cost to exploit that will require some experimentation, just like the other hashes.

**Comment by aschampion** [comment]
This was fixed way back with catsop/python-sopnet@189de83c14ad55cfa10814f25b5b1b637431a09c, catsop/CATMAID@72435bb606cd160b3fd713d533acf1f766ec6221.
