### ISSUE TITLE
SopnetTest initialization parameter issue

### ISSUE THREAD

**Issue by unidesigner** [catsop/catsop#43]
When I try to initialize a SopnetTest object in the Catsop Django environment

```
from tests.testsopnet import SopnetTest
st = SopnetTest(segmentation_configuration_id=2, stack_scale=0)
```

and I have not set any SOPNET_TEST_\* variables in settings.py, I get a ValueError exception:

```
ValueError: Please specify either SOPNET_TEST_STACK_SCALE in your settings or initialize SopnetTest with the appropriate parameters.
```

I don't see anything wrong in the SopnetTest (testsopnet.py) **init** function. For the segmentation_configuration_id it seems to work, but not for stack_scale. Any idea what the issue could be?

Also, what is the idea behind having SOPNET_\* and SOPNET_TEST_\* separation?
Where should the SOPNET_TEST_\* settings go best in the models?

**Comment by aschampion** [comment]
`SOPNET_TEST_*` settings are already stored in the models, in `segmentation_configuration`, `segmentation_block_info`, etc. The `SOPNET_TEST_*` settings are just conveniences for initializing those values when doing lots of testing.

The `SOPNET_*` settings, in contrast, are not stored in the models, because they are actual environment configuration settings, like the path to component storage, database settings, default logging level, etc.

**Comment by aschampion** [comment]
Also to note there is some ambiguity when referencing an existing segmentation configuration about whether the model values or settings values take precedence (especially for block sizes), which I would like to make more clean.
